// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlopenhab

type AddDeviceInput struct {
	RoomID string             `json:"roomID"`
	Device *CreateDeviceInput `json:"device"`
}

type CreateDeviceInput struct {
	Name         string `json:"name"`
	Model        string `json:"model"`
	MacAddress   string `json:"macAddress"`
	Memo         string `json:"memo"`
	SerialNumber string `json:"serialNumber"`
}

type CreateRoomInput struct {
	RoomNumber string               `json:"roomNumber"`
	Memo       string               `json:"memo"`
	Devices    []*CreateDeviceInput `json:"devices"`
}

type Token struct {
	Token    string `json:"token"`
	ExpireAt int    `json:"expireAt"`
}
