// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type DeviceInput struct {
	RoomID       string `json:"roomID"`
	Name         string `json:"name"`
	Model        string `json:"model"`
	MacAddress   string `json:"macAddress"`
	Memo         string `json:"memo"`
	SerialNumber string `json:"serialNumber"`
	Status       int    `json:"status"`
	Type         int    `json:"type"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RoomInput struct {
	RoomNumber string `json:"roomNumber"`
	Memo       string `json:"memo"`
	Username   string `json:"username"`
	Password   string `json:"password"`
}

type UserInput struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Password string `json:"password"`
	Location string `json:"location"`
	Abbr     string `json:"abbr"`
	Email    string `json:"email"`
	Openhab  string `json:"openhab"`
}
